//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TX_Eagle_Supply.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public int Id { get; set; }
        public string EmployeeTypeName { get; set; }
        public string EmployeeTypeDescription { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
