//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMenyBind.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class awEntities : DbContext
    {
        public awEntities()
            : base("name=awEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AWBuildVersion> AWBuildVersions { get; set; }
        public DbSet<DatabaseLog> DatabaseLogs { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<MenuMain> MenuMains { get; set; }
        public DbSet<MenuSub> MenuSubs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserList> UserLists { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
