//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SampleMenuMasterDBModel", "FK_tblLogin_tblRoles", "tblRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DynamicMenyBind.DataModel.tblRole), "tblLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DynamicMenyBind.DataModel.tblLogin), true)]
[assembly: EdmRelationshipAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles", "tblRoles", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DynamicMenyBind.DataModel.tblRole), "tblSubMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DynamicMenyBind.DataModel.tblSubMenu), true)]
[assembly: EdmRelationshipAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles1", "tblMainMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DynamicMenyBind.DataModel.tblMainMenu), "tblSubMenu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DynamicMenyBind.DataModel.tblSubMenu), true)]

#endregion

namespace DynamicMenyBind.DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SampleMenuMasterDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SampleMenuMasterDBEntities object using the connection string found in the 'SampleMenuMasterDBEntities' section of the application configuration file.
        /// </summary>
        public SampleMenuMasterDBEntities() : base("name=SampleMenuMasterDBEntities", "SampleMenuMasterDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleMenuMasterDBEntities object.
        /// </summary>
        public SampleMenuMasterDBEntities(string connectionString) : base(connectionString, "SampleMenuMasterDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleMenuMasterDBEntities object.
        /// </summary>
        public SampleMenuMasterDBEntities(EntityConnection connection) : base(connection, "SampleMenuMasterDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblLogin> tblLogins
        {
            get
            {
                if ((_tblLogins == null))
                {
                    _tblLogins = base.CreateObjectSet<tblLogin>("tblLogins");
                }
                return _tblLogins;
            }
        }
        private ObjectSet<tblLogin> _tblLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMainMenu> tblMainMenus
        {
            get
            {
                if ((_tblMainMenus == null))
                {
                    _tblMainMenus = base.CreateObjectSet<tblMainMenu>("tblMainMenus");
                }
                return _tblMainMenus;
            }
        }
        private ObjectSet<tblMainMenu> _tblMainMenus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRole> tblRoles
        {
            get
            {
                if ((_tblRoles == null))
                {
                    _tblRoles = base.CreateObjectSet<tblRole>("tblRoles");
                }
                return _tblRoles;
            }
        }
        private ObjectSet<tblRole> _tblRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSubMenu> tblSubMenus
        {
            get
            {
                if ((_tblSubMenus == null))
                {
                    _tblSubMenus = base.CreateObjectSet<tblSubMenu>("tblSubMenus");
                }
                return _tblSubMenus;
            }
        }
        private ObjectSet<tblSubMenu> _tblSubMenus;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblLogins(tblLogin tblLogin)
        {
            base.AddObject("tblLogins", tblLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMainMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMainMenus(tblMainMenu tblMainMenu)
        {
            base.AddObject("tblMainMenus", tblMainMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRoles(tblRole tblRole)
        {
            base.AddObject("tblRoles", tblRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSubMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSubMenus(tblSubMenu tblSubMenu)
        {
            base.AddObject("tblSubMenus", tblSubMenu);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleMenuMasterDBModel", Name="tblLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblLogin object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tblLogin CreatetblLogin(global::System.Int32 id)
        {
            tblLogin tblLogin = new tblLogin();
            tblLogin.Id = id;
            return tblLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblLogin_tblRoles", "tblRoles")]
        public tblRole tblRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblRoles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblRoles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblRole> tblRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblRoles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleMenuMasterDBModel", Name="tblMainMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMainMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMainMenu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tblMainMenu CreatetblMainMenu(global::System.Int32 id)
        {
            tblMainMenu tblMainMenu = new tblMainMenu();
            tblMainMenu.Id = id;
            return tblMainMenu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MainMenu
        {
            get
            {
                return _MainMenu;
            }
            set
            {
                OnMainMenuChanging(value);
                ReportPropertyChanging("MainMenu");
                _MainMenu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MainMenu");
                OnMainMenuChanged();
            }
        }
        private global::System.String _MainMenu;
        partial void OnMainMenuChanging(global::System.String value);
        partial void OnMainMenuChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles1", "tblSubMenu")]
        public EntityCollection<tblSubMenu> tblSubMenus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSubMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblSubMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSubMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblSubMenu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleMenuMasterDBModel", Name="tblRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRole object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tblRole CreatetblRole(global::System.Int32 id)
        {
            tblRole tblRole = new tblRole();
            tblRole.Id = id;
            return tblRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblLogin_tblRoles", "tblLogin")]
        public tblLogin tblLogin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLogin>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblLogin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLogin>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblLogin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblLogin> tblLoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblLogin>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblLogin>("SampleMenuMasterDBModel.FK_tblLogin_tblRoles", "tblLogin", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles", "tblSubMenu")]
        public EntityCollection<tblSubMenu> tblSubMenus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSubMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblSubMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSubMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblSubMenu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleMenuMasterDBModel", Name="tblSubMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSubMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSubMenu object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static tblSubMenu CreatetblSubMenu(global::System.Int32 id)
        {
            tblSubMenu tblSubMenu = new tblSubMenu();
            tblSubMenu.Id = id;
            return tblSubMenu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubMenu
        {
            get
            {
                return _SubMenu;
            }
            set
            {
                OnSubMenuChanging(value);
                ReportPropertyChanging("SubMenu");
                _SubMenu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubMenu");
                OnSubMenuChanged();
            }
        }
        private global::System.String _SubMenu;
        partial void OnSubMenuChanging(global::System.String value);
        partial void OnSubMenuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Controller
        {
            get
            {
                return _Controller;
            }
            set
            {
                OnControllerChanging(value);
                ReportPropertyChanging("Controller");
                _Controller = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Controller");
                OnControllerChanged();
            }
        }
        private global::System.String _Controller;
        partial void OnControllerChanging(global::System.String value);
        partial void OnControllerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Action
        {
            get
            {
                return _Action;
            }
            set
            {
                OnActionChanging(value);
                ReportPropertyChanging("Action");
                _Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Action");
                OnActionChanged();
            }
        }
        private global::System.String _Action;
        partial void OnActionChanging(global::System.String value);
        partial void OnActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MainMenuId
        {
            get
            {
                return _MainMenuId;
            }
            set
            {
                OnMainMenuIdChanging(value);
                ReportPropertyChanging("MainMenuId");
                _MainMenuId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MainMenuId");
                OnMainMenuIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MainMenuId;
        partial void OnMainMenuIdChanging(Nullable<global::System.Int32> value);
        partial void OnMainMenuIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleId;
        partial void OnRoleIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles", "tblRoles")]
        public tblRole tblRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblRoles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblRoles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblRole> tblRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblRoles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblRole>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles", "tblRoles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SampleMenuMasterDBModel", "FK_tblSubMenu_tblRoles1", "tblMainMenu")]
        public tblMainMenu tblMainMenu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMainMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblMainMenu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMainMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblMainMenu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblMainMenu> tblMainMenuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblMainMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblMainMenu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblMainMenu>("SampleMenuMasterDBModel.FK_tblSubMenu_tblRoles1", "tblMainMenu", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
