//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_LOGIN_MENU.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.MenuSubs = new HashSet<MenuSub>();
            this.UserLists = new HashSet<UserList>();
        }
    
        public int Id { get; set; }
        public string Roles { get; set; }
    
        public virtual ICollection<MenuSub> MenuSubs { get; set; }
        public virtual ICollection<UserList> UserLists { get; set; }
    }
}
