//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadingDropDownList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public int subcatId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Subcategoryname { get; set; }
    
        public virtual category category { get; set; }
    }
}
